# Generated by Django 5.2.1 on 2025-05-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pizza', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pica',
            name='foto',
        ),
        migrations.AlterField(
            model_name='pica',
            name='cmimi',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
