# Generated by Django 5.2.1 on 2025-05-28 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pizza', '0002_remove_pica_foto_alter_pica_cmimi'),
    ]

    operations = [
        migrations.AddField(
            model_name='pica',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='pica_foto/'),
        ),
    ]
