# Generated by Django 5.2.1 on 2025-05-28 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pizza', '0003_pica_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emri', models.CharField(max_length=100)),
                ('pershkrimi', models.TextField()),
                ('cmimi', models.DecimalField(decimal_places=2, max_digits=5)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='pizza_foto/')),
            ],
        ),
        migrations.DeleteModel(
            name='Pica',
        ),
    ]
