# Generated by Django 5.2.1 on 2025-05-29 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pizza', '0004_pizza_delete_pica'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kontakt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emri', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mesazhi', models.TextField()),
                ('data_dergimit', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
