# Generated by Django 5.2.1 on 2025-05-29 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pizza', '0005_kontakt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pije',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emri', models.CharField(max_length=100)),
                ('pershkrimi', models.TextField(blank=True)),
                ('cmimi', models.DecimalField(decimal_places=2, max_digits=5)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='pijet/')),
            ],
        ),
    ]
