# Generated by Django 5.2.1 on 2025-05-29 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pizza', '0006_pije'),
    ]

    operations = [
        migrations.CreateModel(
            name='Porosi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emri', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('adresa', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('pije', models.ManyToManyField(blank=True, to='Pizza.pije')),
                ('pizza', models.ManyToManyField(blank=True, to='Pizza.pizza')),
            ],
        ),
    ]
