# Generated by Django 5.2.1 on 2025-05-29 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pizza', '0007_porosi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kontakt',
            name='data_dergimit',
        ),
        migrations.RemoveField(
            model_name='porosi',
            name='pije',
        ),
        migrations.RemoveField(
            model_name='porosi',
            name='pizza',
        ),
        migrations.AddField(
            model_name='porosi',
            name='pijet',
            field=models.ManyToManyField(blank=True, to='Pizza.pije'),
        ),
        migrations.AddField(
            model_name='porosi',
            name='pizzat',
            field=models.ManyToManyField(blank=True, to='Pizza.pizza'),
        ),
    ]
