# Generated by Django 5.2.1 on 2025-05-29 17:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pizza', '0008_remove_kontakt_data_dergimit_remove_porosi_pije_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kontakt',
            name='data_dergimit',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
