# Generated by Django 5.2.1 on 2025-05-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pizza', '0009_kontakt_data_dergimit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='porosi',
            name='email',
        ),
        migrations.AddField(
            model_name='porosi',
            name='numri',
            field=models.CharField(default='0000000000', max_length=15),
        ),
    ]
